[package]
name = "grass-latte"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
once_cell = "1.21.3"
tiny_http = "0.12"
tungstenite = "0.26.2"
